### ISSUE TITLE
archive_serializer_map.ipp

### ISSUE THREAD

**Issue by andrewkatson** [bazelboost/serialization#1]
There is a file in `@boost.serialization` that I think is missing. `https://www.boost.org/doc/libs/1_84_0/boost/archive/impl/archive_serializer_map.ipp`

When I use `bazel query 'deps(//something:target) | grep "archive_serializer_map*"` I only see `archive_serializer_map.hpp`. 

Is this intentional?

**Comment by andrewkatson** [comment]
I found the `BUILD` file and I think for `hdrs` you just need to update it to pull in `.ipp` files. :) 

https://github.com/bazelboost/serialization/blob/bazelboost-1.83.0/BUILD.bazel

**Comment by zaucy** [comment]
thanks for the report. I'll get to it soon, but feel free to submit a PR :)

**Comment by andrewkatson** [comment]
I tried but it is saying I don't have permission to push my local branch to the repo. And it looks like `develop` already has the feature.

**Comment by zaucy** [comment]
you have to make a fork in order to contribute to a repository on GitHub. If you're unfamiliar the github CLI can help with this.

also `develop` is an out of date branch, don't worry about that one. Just go off the default branch.

**Comment by andrewkatson** [comment]
Normally I just make a branch and then do a PR from that. But Ill make a fork.

**Comment by andrewkatson** [comment]
Done https://github.com/bazelboost/serialization/pull/2

**Comment by zaucy** [comment]
thanks :) I'll merge and release soon

> Normally I just make a branch and then do a PR from that. But Ill make a fork.

that works fine when you're an owner, member of owning org, or contributor of the repository, but if you're not then a fork is required

**Comment by andrewkatson** [comment]
Ah gotcha well thanks for teaching me something new :)
